### ISSUE TITLE
(vbo) Wonder Project J2: Missing textures with mupen64plus and --osd

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLideN64#1]
OS: `Slackware64-current`
`mesa-2016.09.27_8d8c440_master-x86_64-1_git`
`mupen64plus-2016.09.13_5fa30ab-x86_64-1_git`
`GLupeN64-2016.09.29_5476ed3_master-x86_64-1_git`
`GLideN64-2016.09.27_d5412d3_master-x86_64-1_git`
`GLideN64-vbo-2016.08.15_1306d57_vbo-x86_64-1_git`

During the intro animation in the game `Wonder Project J2` when running mupen64plus with `--osd` which does not support the mesa core profile some textures will be missing. This can of course by worked around with `--noosd`. The below commands will also work around this even with `--osd` although they can cause additional problems.

```
export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
export MESA_GLSL_VERSION_OVERRIDE=430
```

This does not occur with other mupen64plus gfx plugins such as glide64mk2 or z64, upstream GLideN64 or GLupeN64. As a result the main reason to fix this would to make it easier to eventually merge the vbo branch into upstream GLideN64.

apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/mupen64plus/mupen64plus_rsp-hle_GLideN64-vbo_Wonder-Project-J2.trace.xz
apitrace log - http://pastebin.com/Hte1fwNv

**mupen64plus + rsp-hle + GLideN64-vbo**
![gliden64-vbo](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/mupen64plus_rsp-hle_GLideN64-vbo_Wonder-Project-J2_2016-09-29.png)
**mupen64plus + rsp-hle + GLideN64**
![gliden64](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/mupen64plus_rsp-hle_GLideN64_Wonder-Project-J2_2016-09-29.png)
**RetroArch + GLupeN64**
![glupen64](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/retroarch_GLupeN64_Wonder-Project-J2_2016-09-29.png)

**Comment by loganmc10** [comment]
I guess this is a good point, it's not really "my fault", but it does need to get fixed in mupen64plus-core before the VBO branch gets merged, or people are going to have a bad time.

**Comment by orbea** [comment]
Yea, I figured it was not your fault, but this is probably the most reliable place to document it anyways.

**Comment by loganmc10** [comment]
This just got fixed upstream (mupen64plus-core). The OSD will be disabled when an OpenGL context is used, which fixes this problem

**Comment by orbea** [comment]
Cool!
